/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 12, 2017 10:07:52 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.cdac.common.audit.interceptor.IAuditLog;

// TODO: Auto-generated Javadoc
/**
 * Address generated by hbm2java.
 */
@Entity
@Table(name = "address", catalog = "intraop_dev")
public class Address implements java.io.Serializable, IAuditLog
{

	/** The address id. */
	private Integer addressId;

	/** The house no. */
	private String houseNo;

	/** The street. */
	private String street;

	/** The area. */
	private String area;

	/** The location. */
	private String location;

	/** The city village. */
	private String cityVillage;

	/** The district. */
	private String district;

	/** The state. */
	private String state;

	/** The country. */
	private String country;

	/** The pin code. */
	private String pinCode;

	/** The patients. */
	private Set<Patient> patients = new HashSet<Patient>(0);

	/**
	 * Instantiates a new address.
	 */
	public Address()
	{
	}

	/**
	 * Instantiates a new address.
	 *
	 * @param state
	 *            the state
	 * @param country
	 *            the country
	 */
	public Address(String state, String country)
	{
		this.state = state;
		this.country = country;
	}

	/**
	 * Instantiates a new address.
	 *
	 * @param houseNo
	 *            the house no
	 * @param street
	 *            the street
	 * @param area
	 *            the area
	 * @param location
	 *            the location
	 * @param cityVillage
	 *            the city village
	 * @param district
	 *            the district
	 * @param state
	 *            the state
	 * @param country
	 *            the country
	 * @param pinCode
	 *            the pin code
	 * @param patients
	 *            the patients
	 */
	public Address(String houseNo, String street, String area, String location, String cityVillage, String district,
	        String state, String country, String pinCode, Set<Patient> patients)
	{
		this.houseNo = houseNo;
		this.street = street;
		this.area = area;
		this.location = location;
		this.cityVillage = cityVillage;
		this.district = district;
		this.state = state;
		this.country = country;
		this.pinCode = pinCode;
		this.patients = patients;
	}

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/**
	 * Gets the address id.
	 *
	 * @return the address id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AddressID", unique = true, nullable = false)
	public Integer getAddressId()
	{
		return this.addressId;
	}

	/**
	 * Sets the address id.
	 *
	 * @param addressId
	 *            the new address id
	 */
	public void setAddressId(Integer addressId)
	{
		this.addressId = addressId;
	}

	/**
	 * Gets the house no.
	 *
	 * @return the house no
	 */
	@Column(name = "HouseNo", length = 50)
	public String getHouseNo()
	{
		return this.houseNo;
	}

	/**
	 * Sets the house no.
	 *
	 * @param houseNo
	 *            the new house no
	 */
	public void setHouseNo(String houseNo)
	{
		this.houseNo = houseNo;
	}

	/**
	 * Gets the street.
	 *
	 * @return the street
	 */
	@Column(name = "Street", length = 50)
	public String getStreet()
	{
		return this.street;
	}

	/**
	 * Sets the street.
	 *
	 * @param street
	 *            the new street
	 */
	public void setStreet(String street)
	{
		this.street = street;
	}

	/**
	 * Gets the area.
	 *
	 * @return the area
	 */
	@Column(name = "Area", length = 50)
	public String getArea()
	{
		return this.area;
	}

	/**
	 * Sets the area.
	 *
	 * @param area
	 *            the new area
	 */
	public void setArea(String area)
	{
		this.area = area;
	}

	/**
	 * Gets the location.
	 *
	 * @return the location
	 */
	@Column(name = "Location", length = 50)
	public String getLocation()
	{
		return this.location;
	}

	/**
	 * Sets the location.
	 *
	 * @param location
	 *            the new location
	 */
	public void setLocation(String location)
	{
		this.location = location;
	}

	/**
	 * Gets the city village.
	 *
	 * @return the city village
	 */
	@Column(name = "CityVillage", length = 50)
	public String getCityVillage()
	{
		return this.cityVillage;
	}

	/**
	 * Sets the city village.
	 *
	 * @param cityVillage
	 *            the new city village
	 */
	public void setCityVillage(String cityVillage)
	{
		this.cityVillage = cityVillage;
	}

	/**
	 * Gets the district.
	 *
	 * @return the district
	 */
	@Column(name = "District", length = 50)
	public String getDistrict()
	{
		return this.district;
	}

	/**
	 * Sets the district.
	 *
	 * @param district
	 *            the new district
	 */
	public void setDistrict(String district)
	{
		this.district = district;
	}

	/**
	 * Gets the state.
	 *
	 * @return the state
	 */
	@Column(name = "State", nullable = false, length = 50)
	public String getState()
	{
		return this.state;
	}

	/**
	 * Sets the state.
	 *
	 * @param state
	 *            the new state
	 */
	public void setState(String state)
	{
		this.state = state;
	}

	/**
	 * Gets the country.
	 *
	 * @return the country
	 */
	@Column(name = "Country", nullable = false, length = 50)
	public String getCountry()
	{
		return this.country;
	}

	/**
	 * Sets the country.
	 *
	 * @param country
	 *            the new country
	 */
	public void setCountry(String country)
	{
		this.country = country;
	}

	/**
	 * Gets the pin code.
	 *
	 * @return the pin code
	 */
	@Column(name = "PinCode", length = 6)
	public String getPinCode()
	{
		return this.pinCode;
	}

	/**
	 * Sets the pin code.
	 *
	 * @param pinCode
	 *            the new pin code
	 */
	public void setPinCode(String pinCode)
	{
		this.pinCode = pinCode;
	}

	/**
	 * Gets the patients.
	 *
	 * @return the patients
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "address")
	public Set<Patient> getPatients()
	{
		return this.patients;
	}

	/**
	 * Sets the patients.
	 *
	 * @param patients
	 *            the new patients
	 */
	public void setPatients(Set<Patient> patients)
	{
		this.patients = patients;
	}

	@Transient
	@Override
	public Long getId()
	{
		return (long) addressId;
	}

	@Transient
	@Override
	public String getLogDeatil()
	{
		return toString();
	}

	@Transient
	@Override
	public String toString()
	{
		return "AddressEntity [addressID=" + addressId + ", houseNo=" + houseNo + ", street=" + street + ", area="
		        + area + ", location=" + location + ", district=" + district + ", cityVillage=" + cityVillage
		        + ", state=" + state + ", country=" + country + ", pinCode=" + pinCode + "]";
	}

}
