/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 12, 2017 10:07:52 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * Auditlog generated by hbm2java.
 */
@Entity
@Table(name = "auditlog", catalog = "intraop_dev")
public class Auditlog implements java.io.Serializable
{

	/** The audit log id. */
	private Long auditLogId;
	
	/** The login id. */
	private String loginId;
	
	/** The action. */
	private String action;
	
	/** The detail. */
	private String detail;
	
	/** The created date time. */
	private Date createdDateTime;
	
	/** The entity id. */
	private long entityId;
	
	/** The entity name. */
	private String entityName;

	/**
	 * Instantiates a new auditlog.
	 */
	public Auditlog()
	{
	}

	/**
	 * Instantiates a new auditlog.
	 *
	 * @param loginId the login id
	 * @param action the action
	 * @param detail the detail
	 * @param createdDateTime the created date time
	 * @param entityId the entity id
	 * @param entityName the entity name
	 */
	public Auditlog(String loginId, String action, String detail, Date createdDateTime, long entityId,
	        String entityName)
	{
		this.loginId = loginId;
		this.action = action;
		this.detail = detail;
		this.createdDateTime = createdDateTime;
		this.entityId = entityId;
		this.entityName = entityName;
	}

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Gets the audit log id.
	 *
	 * @return the audit log id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AUDIT_LOG_ID", unique = true, nullable = false)
	public Long getAuditLogId()
	{
		return this.auditLogId;
	}

	/**
	 * Sets the audit log id.
	 *
	 * @param auditLogId the new audit log id
	 */
	public void setAuditLogId(Long auditLogId)
	{
		this.auditLogId = auditLogId;
	}

	/**
	 * Gets the login id.
	 *
	 * @return the login id
	 */
	@Column(name = "LOGIN_ID", nullable = false, length = 50)
	public String getLoginId()
	{
		return this.loginId;
	}

	/**
	 * Sets the login id.
	 *
	 * @param loginId the new login id
	 */
	public void setLoginId(String loginId)
	{
		this.loginId = loginId;
	}

	/**
	 * Gets the action.
	 *
	 * @return the action
	 */
	@Column(name = "ACTION", nullable = false, length = 100)
	public String getAction()
	{
		return this.action;
	}

	/**
	 * Sets the action.
	 *
	 * @param action the new action
	 */
	public void setAction(String action)
	{
		this.action = action;
	}

	/**
	 * Gets the detail.
	 *
	 * @return the detail
	 */
	@Column(name = "DETAIL", nullable = false, length = 65535)
	public String getDetail()
	{
		return this.detail;
	}

	/**
	 * Sets the detail.
	 *
	 * @param detail the new detail
	 */
	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	/**
	 * Gets the created date time.
	 *
	 * @return the created date time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE_TIME", nullable = false, length = 19)
	public Date getCreatedDateTime()
	{
		return this.createdDateTime;
	}

	/**
	 * Sets the created date time.
	 *
	 * @param createdDateTime the new created date time
	 */
	public void setCreatedDateTime(Date createdDateTime)
	{
		this.createdDateTime = createdDateTime;
	}

	/**
	 * Gets the entity id.
	 *
	 * @return the entity id
	 */
	@Column(name = "ENTITY_ID", nullable = false)
	public long getEntityId()
	{
		return this.entityId;
	}

	/**
	 * Sets the entity id.
	 *
	 * @param entityId the new entity id
	 */
	public void setEntityId(long entityId)
	{
		this.entityId = entityId;
	}

	/**
	 * Gets the entity name.
	 *
	 * @return the entity name
	 */
	@Column(name = "ENTITY_NAME", nullable = false)
	public String getEntityName()
	{
		return this.entityName;
	}

	/**
	 * Sets the entity name.
	 *
	 * @param entityName the new entity name
	 */
	public void setEntityName(String entityName)
	{
		this.entityName = entityName;
	}

}
