/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Oct 12, 2017 4:52:34 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Deviceconfiguration generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "deviceconfiguration", catalog = "intraop_dev")
public class Deviceconfiguration implements java.io.Serializable {

	private int deviceCongigurationId;
	private int patientId;
	private long caseId;
	private String department;
	private String wardNumber;
	private String model;
	private String serialNumber;
	private String ot;
	private boolean deviceStatus;
	private String portNumber;
	private boolean transportData;
	private String createdBy;
	private Date createdTime;
	private String updatedBy;
	private Date updatedTime;
	private String medicine;

	

	public Deviceconfiguration() 
	{
	}

	public Deviceconfiguration(int deviceCongigurationId, int patientId, long caseId,
			boolean deviceStatus) 
	{
		this.deviceCongigurationId = deviceCongigurationId;
		this.patientId = patientId;
		this.caseId = caseId;
		this.deviceStatus = deviceStatus;
	}






	public Deviceconfiguration(int deviceCongigurationId, int patientId, long caseId, String department,
			String wardNumber, String model, String serialNumber, String ot,  boolean deviceStatus,
			String portNumber, boolean transportData, String createdBy, Date createdTime, String updatedBy,
			Date updatedTime, String medicine) {
		super();
		this.deviceCongigurationId = deviceCongigurationId;
		this.patientId = patientId;
		this.caseId = caseId;
		this.department = department;
		this.wardNumber = wardNumber;
		this.model = model;
		this.serialNumber = serialNumber;
		this.ot = ot;
		this.deviceStatus = deviceStatus;
		this.portNumber = portNumber;
		this.transportData = transportData;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
		this.medicine = medicine;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "DeviceCongigurationID", unique = true, nullable = false)
	public int getDeviceCongigurationId() {
		return this.deviceCongigurationId;
	}

	public void setDeviceCongigurationId(int deviceCongigurationId) {
		this.deviceCongigurationId = deviceCongigurationId;
	}

	public String getSerialNumber() {
		return serialNumber;
	}

	public void setSerialNumber(String serialNumber) {
		this.serialNumber = serialNumber;
	}
	@Column(name = "PatientID", unique = true, nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(int patientId) {
		this.patientId = patientId;
	}

	
	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "CaseID", nullable = false)
	public long getCaseId() {
		return this.caseId;
	}

	public void setCaseId(long caseId) {
		this.caseId = caseId;
	}
	public String getMedicine() {
		return medicine;
	}

	public void setMedicine(String medicine) {
		this.medicine = medicine;
	}

	@Column(name = "Department", length = 250)
	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	@Column(name = "WardNumber", length = 100)
	public String getWardNumber() {
		return this.wardNumber;
	}

	

	public void setWardNumber(String wardNumber) {
		this.wardNumber = wardNumber;
	}

	@Column(name = "OT", length = 250 )
	public String getOt() {
		return ot;
	}

	public void setOt(String ot) {
		this.ot = ot;
	}
	@Column(name = "DeviceStatus", nullable = false)
	public boolean getDeviceStatus() {
		return this.deviceStatus;
	}

	

	public void setDeviceStatus(boolean deviceStatus) {
		this.deviceStatus = deviceStatus;
	}

	@Column(name = "PortNumber", length = 100)
	public String getPortNumber() {
		return portNumber;
	}

	public void setPortNumber(String portNumber) {
		this.portNumber = portNumber;
	}

	@Column(name = "TransportData")
	public boolean getTransportData() {
		return transportData;
	}

	public void setTransportData(boolean transportData) {
		this.transportData = transportData;
	}

	@Column(name = "CreatedBy", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTime", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "UpdatedBy", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTime", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

}
