/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 18, 2017 11:16:42 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diagnosiscategory generated by hbm2java
 */
@Entity
@Table(name = "diagnosiscategory", catalog = "intraop_dev")
public class Diagnosiscategory implements java.io.Serializable
{

	private int diagnosisCategoryId;
	private String diagnosisCategoryValue;
	private String icdversion;
	private Set<Diagnosis> diagnosises = new HashSet<Diagnosis>(0);
	private Set<Diagnosissubcategory> diagnosissubcategories = new HashSet<Diagnosissubcategory>(0);

	public Diagnosiscategory()
	{
	}

	public Diagnosiscategory(int diagnosisCategoryId, String diagnosisCategoryValue)
	{
		this.diagnosisCategoryId = diagnosisCategoryId;
		this.diagnosisCategoryValue = diagnosisCategoryValue;
	}

	public Diagnosiscategory(int diagnosisCategoryId, String diagnosisCategoryValue, String icdversion,
	        Set<Diagnosis> diagnosises, Set<Diagnosissubcategory> diagnosissubcategories)
	{
		this.diagnosisCategoryId = diagnosisCategoryId;
		this.diagnosisCategoryValue = diagnosisCategoryValue;
		this.icdversion = icdversion;
		this.diagnosises = diagnosises;
		this.diagnosissubcategories = diagnosissubcategories;
	}

	@Id

	@Column(name = "DiagnosisCategoryID", unique = true, nullable = false)
	public int getDiagnosisCategoryId()
	{
		return this.diagnosisCategoryId;
	}

	public void setDiagnosisCategoryId(int diagnosisCategoryId)
	{
		this.diagnosisCategoryId = diagnosisCategoryId;
	}

	@Column(name = "DiagnosisCategoryValue", nullable = false, length = 200)
	public String getDiagnosisCategoryValue()
	{
		return this.diagnosisCategoryValue;
	}

	public void setDiagnosisCategoryValue(String diagnosisCategoryValue)
	{
		this.diagnosisCategoryValue = diagnosisCategoryValue;
	}

	@Column(name = "ICDVersion", length = 25)
	public String getIcdversion()
	{
		return this.icdversion;
	}

	public void setIcdversion(String icdversion)
	{
		this.icdversion = icdversion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosiscategory")
	public Set<Diagnosis> getDiagnosises()
	{
		return this.diagnosises;
	}

	public void setDiagnosises(Set<Diagnosis> diagnosises)
	{
		this.diagnosises = diagnosises;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosiscategory")
	public Set<Diagnosissubcategory> getDiagnosissubcategories()
	{
		return this.diagnosissubcategories;
	}

	public void setDiagnosissubcategories(Set<Diagnosissubcategory> diagnosissubcategories)
	{
		this.diagnosissubcategories = diagnosissubcategories;
	}

}
