/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 18, 2017 11:16:42 AM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Diagnosissubcategory generated by hbm2java
 */
@Entity
@Table(name = "diagnosissubcategory", catalog = "intraop_dev")
public class Diagnosissubcategory implements java.io.Serializable
{

	private Integer diagnosisSubCategory;
	private Diagnosiscategory diagnosiscategory;
	private String diagnosisSubcategoryValue;
	private String icdversion;
	private Set<Diagnosis> diagnosises = new HashSet<Diagnosis>(0);

	public Diagnosissubcategory()
	{
	}

	public Diagnosissubcategory(Diagnosiscategory diagnosiscategory, String diagnosisSubcategoryValue,
	        String icdversion, Set<Diagnosis> diagnosises)
	{
		this.diagnosiscategory = diagnosiscategory;
		this.diagnosisSubcategoryValue = diagnosisSubcategoryValue;
		this.icdversion = icdversion;
		this.diagnosises = diagnosises;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DiagnosisSubCategory", unique = true, nullable = false)
	public Integer getDiagnosisSubCategory()
	{
		return this.diagnosisSubCategory;
	}

	public void setDiagnosisSubCategory(Integer diagnosisSubCategory)
	{
		this.diagnosisSubCategory = diagnosisSubCategory;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "DiagnosisCategoryID")
	public Diagnosiscategory getDiagnosiscategory()
	{
		return this.diagnosiscategory;
	}

	public void setDiagnosiscategory(Diagnosiscategory diagnosiscategory)
	{
		this.diagnosiscategory = diagnosiscategory;
	}

	@Column(name = "DiagnosisSubcategoryValue", length = 200)
	public String getDiagnosisSubcategoryValue()
	{
		return this.diagnosisSubcategoryValue;
	}

	public void setDiagnosisSubcategoryValue(String diagnosisSubcategoryValue)
	{
		this.diagnosisSubcategoryValue = diagnosisSubcategoryValue;
	}

	@Column(name = "ICDVersion", length = 25)
	public String getIcdversion()
	{
		return this.icdversion;
	}

	public void setIcdversion(String icdversion)
	{
		this.icdversion = icdversion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "diagnosissubcategory")
	public Set<Diagnosis> getDiagnosises()
	{
		return this.diagnosises;
	}

	public void setDiagnosises(Set<Diagnosis> diagnosises)
	{
		this.diagnosises = diagnosises;
	}

}
