/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Oct 4, 2017 5:48:43 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fdamedications generated by hbm2java
 */
@Entity
@Table(name = "fdaintraopmedications", catalog = "intraop_dev")
public class Fdamedications implements java.io.Serializable
{

	private Integer medicationsId;
	private String medicationsName;
	private Boolean isFavourite;
	private String defaultUnit;
	private String order;

	public Fdamedications()
	{
	}

	public Fdamedications(String medicationsName, Boolean isFavourite)
	{
		this.medicationsName = medicationsName;
		this.isFavourite = isFavourite;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "MedicationsID", unique = true, nullable = false)
	public Integer getMedicationsId()
	{
		return this.medicationsId;
	}

	public void setMedicationsId(Integer medicationsId)
	{
		this.medicationsId = medicationsId;
	}

	@Column(name = "MedicationsName", length = 1000)
	public String getMedicationsName()
	{
		return this.medicationsName;
	}

	public void setMedicationsName(String medicationsName)
	{
		this.medicationsName = medicationsName;
	}

	@Column(name = "IsFavourite")
	public Boolean getIsFavourite()
	{
		return this.isFavourite;
	}

	public void setIsFavourite(Boolean isFavourite)
	{
		this.isFavourite = isFavourite;
	}

	@Column(name = "DefaultUnit", length = 45)
	public String getDefaultUnit()
	{
		return this.defaultUnit;
	}

	public void setDefaultUnit(String defaultUnit)
	{
		this.defaultUnit = defaultUnit;
	}

	@Column(name = "DefaultOrder")
	public String getOrder()
	{
		return this.order;
	}

	public void setOrder(String order)
	{
		this.order = order;
	}

}
