/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 12, 2017 10:07:52 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * IntraopSurgicalsafetychecklist generated by hbm2java.
 */
@Entity
@Table(name = "intraop_surgicalsafetychecklist", catalog = "intraop_dev")
public class IntraopSurgicalsafetychecklist implements java.io.Serializable
{

	/** The checklist id. */
	private int checklistId;
	
	/** The checklist name. */
	private String checklistName;
	
	/** The checks. */
	private String checks;
	
	/** The created by. */
	private String createdBy;
	
	/** The created time. */
	private Date createdTime;
	
	/** The updated by. */
	private String updatedBy;
	
	/** The updated time. */
	private Date updatedTime;
	
	/** The intraop surgicalsafeties. */
	private Set<IntraopSurgicalsafety> intraopSurgicalsafeties = new HashSet<IntraopSurgicalsafety>(0);

	/**
	 * Instantiates a new intraop surgicalsafetychecklist.
	 */
	public IntraopSurgicalsafetychecklist()
	{
	}

	/**
	 * Instantiates a new intraop surgicalsafetychecklist.
	 *
	 * @param checklistId the checklist id
	 */
	public IntraopSurgicalsafetychecklist(int checklistId)
	{
		this.checklistId = checklistId;
	}

	/**
	 * Instantiates a new intraop surgicalsafetychecklist.
	 *
	 * @param checklistId the checklist id
	 * @param checklistName the checklist name
	 * @param checks the checks
	 * @param createdBy the created by
	 * @param createdTime the created time
	 * @param updatedBy the updated by
	 * @param updatedTime the updated time
	 * @param intraopSurgicalsafeties the intraop surgicalsafeties
	 */
	public IntraopSurgicalsafetychecklist(int checklistId, String checklistName, String checks, String createdBy,
	        Date createdTime, String updatedBy, Date updatedTime, Set<IntraopSurgicalsafety> intraopSurgicalsafeties)
	{
		this.checklistId = checklistId;
		this.checklistName = checklistName;
		this.checks = checks;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
		this.intraopSurgicalsafeties = intraopSurgicalsafeties;
	}

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Gets the checklist id.
	 *
	 * @return the checklist id
	 */
	@Id

	@Column(name = "ChecklistID", unique = true, nullable = false)
	public int getChecklistId()
	{
		return this.checklistId;
	}

	/**
	 * Sets the checklist id.
	 *
	 * @param checklistId the new checklist id
	 */
	public void setChecklistId(int checklistId)
	{
		this.checklistId = checklistId;
	}

	/**
	 * Gets the checklist name.
	 *
	 * @return the checklist name
	 */
	@Column(name = "ChecklistName", length = 45)
	public String getChecklistName()
	{
		return this.checklistName;
	}

	/**
	 * Sets the checklist name.
	 *
	 * @param checklistName the new checklist name
	 */
	public void setChecklistName(String checklistName)
	{
		this.checklistName = checklistName;
	}

	/**
	 * Gets the checks.
	 *
	 * @return the checks
	 */
	@Column(name = "Checks", length = 45)
	public String getChecks()
	{
		return this.checks;
	}

	/**
	 * Sets the checks.
	 *
	 * @param checks the new checks
	 */
	public void setChecks(String checks)
	{
		this.checks = checks;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "CreatedBy", length = 45)
	public String getCreatedBy()
	{
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Gets the created time.
	 *
	 * @return the created time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTime", length = 19)
	public Date getCreatedTime()
	{
		return this.createdTime;
	}

	/**
	 * Sets the created time.
	 *
	 * @param createdTime the new created time
	 */
	public void setCreatedTime(Date createdTime)
	{
		this.createdTime = createdTime;
	}

	/**
	 * Gets the updated by.
	 *
	 * @return the updated by
	 */
	@Column(name = "UpdatedBy", length = 45)
	public String getUpdatedBy()
	{
		return this.updatedBy;
	}

	/**
	 * Sets the updated by.
	 *
	 * @param updatedBy the new updated by
	 */
	public void setUpdatedBy(String updatedBy)
	{
		this.updatedBy = updatedBy;
	}

	/**
	 * Gets the updated time.
	 *
	 * @return the updated time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTime", length = 19)
	public Date getUpdatedTime()
	{
		return this.updatedTime;
	}

	/**
	 * Sets the updated time.
	 *
	 * @param updatedTime the new updated time
	 */
	public void setUpdatedTime(Date updatedTime)
	{
		this.updatedTime = updatedTime;
	}

	/**
	 * Gets the intraop surgicalsafeties.
	 *
	 * @return the intraop surgicalsafeties
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intraopSurgicalsafetychecklist")
	public Set<IntraopSurgicalsafety> getIntraopSurgicalsafeties()
	{
		return this.intraopSurgicalsafeties;
	}

	/**
	 * Sets the intraop surgicalsafeties.
	 *
	 * @param intraopSurgicalsafeties the new intraop surgicalsafeties
	 */
	public void setIntraopSurgicalsafeties(Set<IntraopSurgicalsafety> intraopSurgicalsafeties)
	{
		this.intraopSurgicalsafeties = intraopSurgicalsafeties;
	}

}
