/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 12, 2017 10:07:52 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// TODO: Auto-generated Javadoc
/**
 * IntraopDevices generated by hbm2java.
 */
@Entity
@Table(name = "intraop_devices", catalog = "intraop_dev")
public class IntraopDevices implements java.io.Serializable
{

	/** The device id. */
	private Integer deviceId;
	
	/** The intraop location. */
	private IntraopLocation intraopLocation;
	
	/** The serial number. */
	private String serialNumber;
	
	/** The make. */
	private String make;
	
	/** The model. */
	private String model;
	
	/** The type. */
	private String type;
	
	/** The status. */
	private String status;
	
	/** The created by. */
	private String createdBy;
	
	/** The created time. */
	private Date createdTime;
	
	/** The updated by. */
	private String updatedBy;
	
	/** The updated time. */
	private Date updatedTime;
	
	/** The intraop patientdevicemappings. */
	private Set<IntraopPatientdevicemapping> intraopPatientdevicemappings = new HashSet<IntraopPatientdevicemapping>(0);

	/**
	 * Instantiates a new intraop devices.
	 */
	public IntraopDevices()
	{
	}

	/**
	 * Instantiates a new intraop devices.
	 *
	 * @param intraopLocation the intraop location
	 * @param serialNumber the serial number
	 * @param make the make
	 * @param model the model
	 * @param type the type
	 * @param status the status
	 * @param createdBy the created by
	 * @param createdTime the created time
	 * @param updatedBy the updated by
	 * @param updatedTime the updated time
	 * @param intraopPatientdevicemappings the intraop patientdevicemappings
	 */
	public IntraopDevices(IntraopLocation intraopLocation, String serialNumber, String make, String model, String type,
	        String status, String createdBy, Date createdTime, String updatedBy, Date updatedTime,
	        Set<IntraopPatientdevicemapping> intraopPatientdevicemappings)
	{
		this.intraopLocation = intraopLocation;
		this.serialNumber = serialNumber;
		this.make = make;
		this.model = model;
		this.type = type;
		this.status = status;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
		this.intraopPatientdevicemappings = intraopPatientdevicemappings;
	}
	
	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/**
	 * Gets the device id.
	 *
	 * @return the device id
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "DeviceID", unique = true, nullable = false)
	public Integer getDeviceId()
	{
		return this.deviceId;
	}

	/**
	 * Sets the device id.
	 *
	 * @param deviceId the new device id
	 */
	public void setDeviceId(Integer deviceId)
	{
		this.deviceId = deviceId;
	}

	/**
	 * Gets the intraop location.
	 *
	 * @return the intraop location
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "LocationID")
	public IntraopLocation getIntraopLocation()
	{
		return this.intraopLocation;
	}

	/**
	 * Sets the intraop location.
	 *
	 * @param intraopLocation the new intraop location
	 */
	public void setIntraopLocation(IntraopLocation intraopLocation)
	{
		this.intraopLocation = intraopLocation;
	}

	/**
	 * Gets the serial number.
	 *
	 * @return the serial number
	 */
	@Column(name = "SerialNumber", length = 45)
	public String getSerialNumber()
	{
		return this.serialNumber;
	}

	/**
	 * Sets the serial number.
	 *
	 * @param serialNumber the new serial number
	 */
	public void setSerialNumber(String serialNumber)
	{
		this.serialNumber = serialNumber;
	}

	/**
	 * Gets the make.
	 *
	 * @return the make
	 */
	@Column(name = "Make", length = 45)
	public String getMake()
	{
		return this.make;
	}

	/**
	 * Sets the make.
	 *
	 * @param make the new make
	 */
	public void setMake(String make)
	{
		this.make = make;
	}

	/**
	 * Gets the model.
	 *
	 * @return the model
	 */
	@Column(name = "Model", length = 45)
	public String getModel()
	{
		return this.model;
	}

	/**
	 * Sets the model.
	 *
	 * @param model the new model
	 */
	public void setModel(String model)
	{
		this.model = model;
	}

	/**
	 * Gets the type.
	 *
	 * @return the type
	 */
	@Column(name = "Type", length = 45)
	public String getType()
	{
		return this.type;
	}

	/**
	 * Sets the type.
	 *
	 * @param type the new type
	 */
	public void setType(String type)
	{
		this.type = type;
	}

	/**
	 * Gets the status.
	 *
	 * @return the status
	 */
	@Column(name = "Status", length = 45)
	public String getStatus()
	{
		return this.status;
	}

	/**
	 * Sets the status.
	 *
	 * @param status the new status
	 */
	public void setStatus(String status)
	{
		this.status = status;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "CreatedBy", length = 45)
	public String getCreatedBy()
	{
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Gets the created time.
	 *
	 * @return the created time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTime", length = 19)
	public Date getCreatedTime()
	{
		return this.createdTime;
	}

	/**
	 * Sets the created time.
	 *
	 * @param createdTime the new created time
	 */
	public void setCreatedTime(Date createdTime)
	{
		this.createdTime = createdTime;
	}

	/**
	 * Gets the updated by.
	 *
	 * @return the updated by
	 */
	@Column(name = "UpdatedBy", length = 45)
	public String getUpdatedBy()
	{
		return this.updatedBy;
	}

	/**
	 * Sets the updated by.
	 *
	 * @param updatedBy the new updated by
	 */
	public void setUpdatedBy(String updatedBy)
	{
		this.updatedBy = updatedBy;
	}

	/**
	 * Gets the updated time.
	 *
	 * @return the updated time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTime", length = 19)
	public Date getUpdatedTime()
	{
		return this.updatedTime;
	}

	/**
	 * Sets the updated time.
	 *
	 * @param updatedTime the new updated time
	 */
	public void setUpdatedTime(Date updatedTime)
	{
		this.updatedTime = updatedTime;
	}

	/**
	 * Gets the intraop patientdevicemappings.
	 *
	 * @return the intraop patientdevicemappings
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "intraopDevices")
	public Set<IntraopPatientdevicemapping> getIntraopPatientdevicemappings()
	{
		return this.intraopPatientdevicemappings;
	}

	/**
	 * Sets the intraop patientdevicemappings.
	 *
	 * @param intraopPatientdevicemappings the new intraop patientdevicemappings
	 */
	public void setIntraopPatientdevicemappings(Set<IntraopPatientdevicemapping> intraopPatientdevicemappings)
	{
		this.intraopPatientdevicemappings = intraopPatientdevicemappings;
	}

}
