/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Oct 27, 2017 4:53:31 PM by Hibernate Tools 4.3.5.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.cdac.common.GeneratedEntities.Patient;
import com.cdac.common.GeneratedEntities.Patientcase;
import com.cdac.common.audit.interceptor.IAuditLog;

/**
 * IntraopAnesthesiarecord generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "intraop_anesthesiarecord", catalog = "intraop_dev")
public class IntraopAnesthesiarecord implements java.io.Serializable ,IAuditLog{

	private Integer anesthesiaRecordId;
	private Patient patient;
	private Patientcase patientcase;
	private String gaInduction;
	private String gaAirway;
	private String gaMaskComment;
	private String gaSupraglotticSize;
	private String gaSupraglotticAttempts;
	private String gaSupraglotticComment;
	private String gaEttsize;
	private String gaEttattempts;
	private String gaEttfixedAt;
	private String gaEttcomment;
	private String gaVentilation;
	private String gaAirPressure;
	private String gaFiO2;
	private String gaVt;
	private String gaRr;
	private String gaIe;
	private String gaVentilationComment;
	private String raSpinalSite;
	private String raSpinalNeedle;
	private String raSpinalHsl;
	private String raEpiduralSite;
	private String raEpiduralNeedle;
	private String raEpiduralCfixedAt;
	private String raUlbsite;
	private String raUlbBpbapproach;
	private String raUlbPnbapproach;
	private String raLlbsite;
	private String raLlbLpnbapproach;
	private String raLlbSpnbapproach;
	private String raComments;
	private String raTcnbapproach;
	private String raTcnbcomment;
	private String macComment;
	private String createdBy;
	private Date createdTime;
	private String updatedBy;
	private Date updatedTime;
	private String cuffedUncuffed;



	public IntraopAnesthesiarecord() {
	}

	public IntraopAnesthesiarecord(Patient patient, Patientcase patientcase) {
		this.patient = patient;
		this.patientcase = patientcase;
	}

	public IntraopAnesthesiarecord(Patient patient, Patientcase patientcase, String gaInduction, String gaAirway,
			String gaMaskComment, String gaSupraglotticSize, String gaSupraglotticAttempts,
			String gaSupraglotticComment, String gaEttsize, String gaEttattempts, String gaEttfixedAt,
			String gaEttcomment, String gaVentilation, String gaAirPressure, String gaFiO2, String gaVt, String gaRr,
			String gaIe, String gaVentilationComment, String raSpinalSite, String raSpinalNeedle, String raSpinalHsl,
			String raEpiduralSite, String raEpiduralNeedle, String raEpiduralCfixedAt, String raUlbsite,
			String raUlbBpbapproach, String raUlbPnbapproach, String raLlbsite, String raLlbLpnbapproach,
			String raLlbSpnbapproach, String raComments, String raTcnbapproach, String raTcnbcomment, String macComment,
			String createdBy, Date createdTime, String updatedBy, Date updatedTime) {
		this.patient = patient;
		this.patientcase = patientcase;
		this.gaInduction = gaInduction;
		this.gaAirway = gaAirway;
		this.gaMaskComment = gaMaskComment;
		this.gaSupraglotticSize = gaSupraglotticSize;
		this.gaSupraglotticAttempts = gaSupraglotticAttempts;
		this.gaSupraglotticComment = gaSupraglotticComment;
		this.gaEttsize = gaEttsize;
		this.gaEttattempts = gaEttattempts;
		this.gaEttfixedAt = gaEttfixedAt;
		this.gaEttcomment = gaEttcomment;
		this.gaVentilation = gaVentilation;
		this.gaAirPressure = gaAirPressure;
		this.gaFiO2 = gaFiO2;
		this.gaVt = gaVt;
		this.gaRr = gaRr;
		this.gaIe = gaIe;
		this.gaVentilationComment = gaVentilationComment;
		this.raSpinalSite = raSpinalSite;
		this.raSpinalNeedle = raSpinalNeedle;
		this.raSpinalHsl = raSpinalHsl;
		this.raEpiduralSite = raEpiduralSite;
		this.raEpiduralNeedle = raEpiduralNeedle;
		this.raEpiduralCfixedAt = raEpiduralCfixedAt;
		this.raUlbsite = raUlbsite;
		this.raUlbBpbapproach = raUlbBpbapproach;
		this.raUlbPnbapproach = raUlbPnbapproach;
		this.raLlbsite = raLlbsite;
		this.raLlbLpnbapproach = raLlbLpnbapproach;
		this.raLlbSpnbapproach = raLlbSpnbapproach;
		this.raComments = raComments;
		this.raTcnbapproach = raTcnbapproach;
		this.raTcnbcomment = raTcnbcomment;
		this.macComment = macComment;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AnesthesiaRecordID", unique = true, nullable = false)
	public Integer getAnesthesiaRecordId() {
		return this.anesthesiaRecordId;
	}

	public void setAnesthesiaRecordId(Integer anesthesiaRecordId) {
		this.anesthesiaRecordId = anesthesiaRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientID", nullable = false)
	public Patient getPatient() {
		return this.patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CaseID", nullable = false)
	public Patientcase getPatientcase() {
		return this.patientcase;
	}

	public void setPatientcase(Patientcase patientcase) {
		this.patientcase = patientcase;
	}

	@Column(name = "GA_Induction", length = 45)
	public String getGaInduction() {
		return this.gaInduction;
	}

	public void setGaInduction(String gaInduction) {
		this.gaInduction = gaInduction;
	}

	@Column(name = "GA_Airway", length = 45)
	public String getGaAirway() {
		return this.gaAirway;
	}

	public void setGaAirway(String gaAirway) {
		this.gaAirway = gaAirway;
	}

	@Column(name = "GA_MaskComment", length = 2000)
	public String getGaMaskComment() {
		return this.gaMaskComment;
	}

	public void setGaMaskComment(String gaMaskComment) {
		this.gaMaskComment = gaMaskComment;
	}

	@Column(name = "GA_SupraglotticSize", length = 45)
	public String getGaSupraglotticSize() {
		return this.gaSupraglotticSize;
	}

	public void setGaSupraglotticSize(String gaSupraglotticSize) {
		this.gaSupraglotticSize = gaSupraglotticSize;
	}

	@Column(name = "GA_SupraglotticAttempts", length = 45)
	public String getGaSupraglotticAttempts() {
		return this.gaSupraglotticAttempts;
	}

	public void setGaSupraglotticAttempts(String gaSupraglotticAttempts) {
		this.gaSupraglotticAttempts = gaSupraglotticAttempts;
	}

	@Column(name = "GA_SupraglotticComment", length = 2000)
	public String getGaSupraglotticComment() {
		return this.gaSupraglotticComment;
	}

	public void setGaSupraglotticComment(String gaSupraglotticComment) {
		this.gaSupraglotticComment = gaSupraglotticComment;
	}

	@Column(name = "GA_ETTSize", length = 45)
	public String getGaEttsize() {
		return this.gaEttsize;
	}

	public void setGaEttsize(String gaEttsize) {
		this.gaEttsize = gaEttsize;
	}

	@Column(name = "GA_ETTAttempts", length = 45)
	public String getGaEttattempts() {
		return this.gaEttattempts;
	}

	public void setGaEttattempts(String gaEttattempts) {
		this.gaEttattempts = gaEttattempts;
	}

	@Column(name = "GA_ETTFixedAt", length = 45)
	public String getGaEttfixedAt() {
		return this.gaEttfixedAt;
	}

	public void setGaEttfixedAt(String gaEttfixedAt) {
		this.gaEttfixedAt = gaEttfixedAt;
	}

	@Column(name = "GA_ETTComment", length = 2000)
	public String getGaEttcomment() {
		return this.gaEttcomment;
	}

	public void setGaEttcomment(String gaEttcomment) {
		this.gaEttcomment = gaEttcomment;
	}

	@Column(name = "GA_Ventilation", length = 45)
	public String getGaVentilation() {
		return this.gaVentilation;
	}

	public void setGaVentilation(String gaVentilation) {
		this.gaVentilation = gaVentilation;
	}

	@Column(name = "GA_AirPressure", length = 45)
	public String getGaAirPressure() {
		return this.gaAirPressure;
	}

	public void setGaAirPressure(String gaAirPressure) {
		this.gaAirPressure = gaAirPressure;
	}

	@Column(name = "GA_FiO2", length = 45)
	public String getGaFiO2() {
		return this.gaFiO2;
	}

	public void setGaFiO2(String gaFiO2) {
		this.gaFiO2 = gaFiO2;
	}

	@Column(name = "GA_VT", length = 45)
	public String getGaVt() {
		return this.gaVt;
	}

	public void setGaVt(String gaVt) {
		this.gaVt = gaVt;
	}

	@Column(name = "GA_RR", length = 45)
	public String getGaRr() {
		return this.gaRr;
	}

	public void setGaRr(String gaRr) {
		this.gaRr = gaRr;
	}

	@Column(name = "GA_IE", length = 45)
	public String getGaIe() {
		return this.gaIe;
	}

	public void setGaIe(String gaIe) {
		this.gaIe = gaIe;
	}

	@Column(name = "GA_VentilationComment", length = 2000)
	public String getGaVentilationComment() {
		return this.gaVentilationComment;
	}

	public void setGaVentilationComment(String gaVentilationComment) {
		this.gaVentilationComment = gaVentilationComment;
	}

	@Column(name = "RA_SpinalSite", length = 45)
	public String getRaSpinalSite() {
		return this.raSpinalSite;
	}

	public void setRaSpinalSite(String raSpinalSite) {
		this.raSpinalSite = raSpinalSite;
	}

	@Column(name = "RA_SpinalNeedle", length = 45)
	public String getRaSpinalNeedle() {
		return this.raSpinalNeedle;
	}

	public void setRaSpinalNeedle(String raSpinalNeedle) {
		this.raSpinalNeedle = raSpinalNeedle;
	}

	@Column(name = "RA_SpinalHsl", length = 45)
	public String getRaSpinalHsl() {
		return this.raSpinalHsl;
	}

	public void setRaSpinalHsl(String raSpinalHsl) {
		this.raSpinalHsl = raSpinalHsl;
	}

	@Column(name = "RA_EpiduralSite", length = 45)
	public String getRaEpiduralSite() {
		return this.raEpiduralSite;
	}

	public void setRaEpiduralSite(String raEpiduralSite) {
		this.raEpiduralSite = raEpiduralSite;
	}

	@Column(name = "RA_EpiduralNeedle", length = 45)
	public String getRaEpiduralNeedle() {
		return this.raEpiduralNeedle;
	}

	public void setRaEpiduralNeedle(String raEpiduralNeedle) {
		this.raEpiduralNeedle = raEpiduralNeedle;
	}

	@Column(name = "RA_EpiduralCfixedAt", length = 45)
	public String getRaEpiduralCfixedAt() {
		return this.raEpiduralCfixedAt;
	}

	public void setRaEpiduralCfixedAt(String raEpiduralCfixedAt) {
		this.raEpiduralCfixedAt = raEpiduralCfixedAt;
	}

	@Column(name = "RA_Ulbsite", length = 45)
	public String getRaUlbsite() {
		return this.raUlbsite;
	}

	public void setRaUlbsite(String raUlbsite) {
		this.raUlbsite = raUlbsite;
	}

	@Column(name = "RA_UlbBpbapproach", length = 45)
	public String getRaUlbBpbapproach() {
		return this.raUlbBpbapproach;
	}

	public void setRaUlbBpbapproach(String raUlbBpbapproach) {
		this.raUlbBpbapproach = raUlbBpbapproach;
	}

	@Column(name = "RA_UlbPnbapproach", length = 45)
	public String getRaUlbPnbapproach() {
		return this.raUlbPnbapproach;
	}

	public void setRaUlbPnbapproach(String raUlbPnbapproach) {
		this.raUlbPnbapproach = raUlbPnbapproach;
	}

	@Column(name = "RA_Llbsite", length = 45)
	public String getRaLlbsite() {
		return this.raLlbsite;
	}

	public void setRaLlbsite(String raLlbsite) {
		this.raLlbsite = raLlbsite;
	}

	@Column(name = "RA_LlbLpnbapproach", length = 45)
	public String getRaLlbLpnbapproach() {
		return this.raLlbLpnbapproach;
	}

	public void setRaLlbLpnbapproach(String raLlbLpnbapproach) {
		this.raLlbLpnbapproach = raLlbLpnbapproach;
	}

	@Column(name = "RA_LlbSpnbapproach", length = 45)
	public String getRaLlbSpnbapproach() {
		return this.raLlbSpnbapproach;
	}

	public void setRaLlbSpnbapproach(String raLlbSpnbapproach) {
		this.raLlbSpnbapproach = raLlbSpnbapproach;
	}

	@Column(name = "RA_Comments", length = 2000)
	public String getRaComments() {
		return this.raComments;
	}

	public void setRaComments(String raComments) {
		this.raComments = raComments;
	}

	@Column(name = "RA_TCNBApproach", length = 45)
	public String getRaTcnbapproach() {
		return this.raTcnbapproach;
	}

	public void setRaTcnbapproach(String raTcnbapproach) {
		this.raTcnbapproach = raTcnbapproach;
	}

	@Column(name = "RA_TCNBComment", length = 45)
	public String getRaTcnbcomment() {
		return this.raTcnbcomment;
	}

	public void setRaTcnbcomment(String raTcnbcomment) {
		this.raTcnbcomment = raTcnbcomment;
	}

	@Column(name = "MAC_Comment", length = 2000)
	public String getMacComment() {
		return this.macComment;
	}

	public void setMacComment(String macComment) {
		this.macComment = macComment;
	}
	@Column(name = "CoughedUncoughed", length = 45)
	public String getcuffedUncuffed() {
		return cuffedUncuffed;
	}

	public void setcuffedUncuffed(String cuffedUncuffed) {
		this.cuffedUncuffed = cuffedUncuffed;
	}
	@Column(name = "CreatedBy", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTime", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "UpdatedBy", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTime", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}
	@Transient
	@Override
	public Long getId()
	{
		return (long) anesthesiaRecordId;
	}

	@Transient
	@Override
	public String getLogDeatil()
	{
		return toString();
	}

	@Transient
	@Override
	public String toString()
	{
		return "IntraopMedicationLogEntity [AnesthesiaRecordID=" + anesthesiaRecordId + ",PatientID="
		        + patient.getPatientId() + ",CaseID=" + patientcase.getCaseId() + ",GA_Induction=" + gaInduction
		        + ",GA_Airway=" + gaAirway + ",GA_MaskComment=" + gaMaskComment + ",GA_SupraglotticSize="
		        + gaSupraglotticSize + ",GA_SupraglotticAttempts=" + gaSupraglotticAttempts + ",GA_SupraglotticComment="
		        + gaSupraglotticComment + ",GA_ETTSize=" + gaEttsize + ",GA_ETTAttempts=" + gaEttattempts
		        + ",GA_ETTFixedAt=" + gaEttfixedAt + ",GA_ETTComment=" + gaEttcomment + ",GA_Ventilation="
		        + gaVentilation + ",GA_AirPressure=" + gaAirPressure + ",GA_FiO2=" + gaFiO2 + ",GA_VT=" + gaVt
		        + ",GA_RR=" + gaRr + ",GA_IE=" + gaIe + ",GA_VentilationComment=" + gaVentilationComment
		        + ",RA_SpinalSite=" + raSpinalSite + ",RA_SpinalNeedle=" + raSpinalNeedle + ",RA_SpinalHSL="
		        + raSpinalHsl +",RA_EPIDuralSite=" + raEpiduralSite
		        + ",RA_EPIDuralNeedle=" + raEpiduralNeedle + ",RA_EPIDuralCFixedAt=" + raEpiduralCfixedAt
		        + ",RA_ULBSite=" + raUlbsite +",RA_ULB_BPBApproach="
		        + raUlbBpbapproach + ",RA_ULB_PNBApproach=" + raUlbPnbapproach +",RA_LLBSite=" + raLlbsite + ",RA_LLB_LPNBApproach=" + raLlbLpnbapproach + ",RA_LLB_SPNBApproach="
		        + raLlbSpnbapproach +", RA_Comment=" + raComments + ",RA_TCNBApproach=" + raTcnbapproach
		        + ",RA_TCNBComment=" + raTcnbcomment + ",MAC_Comment=" + macComment + ",CreatedBy="
		        + createdBy + ", CreatedTime="
		        + createdTime + ", UpdatedBy=" + updatedBy + ", UpdatedTime=" + updatedTime + "]";
	}

}
