/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 12, 2017 10:07:52 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

// TODO: Auto-generated Javadoc
/**
 * IntraopSurgicalsafetyId generated by hbm2java.
 */
@Embeddable
public class IntraopSurgicalsafetyId implements java.io.Serializable
{

	/** The surgery checklist id. */
	private Integer surgeryChecklistId;
	
	/** The name. */
	private String name;
	
	/** The order. */
	private Integer order;
	
	/** The created by. */
	private String createdBy;
	
	/** The created time. */
	private Date createdTime;
	
	/** The updated by. */
	private String updatedBy;
	
	/** The updated time. */
	private Date updatedTime;

	/**
	 * Instantiates a new intraop surgicalsafety id.
	 */
	public IntraopSurgicalsafetyId()
	{
	}

	/**
	 * Instantiates a new intraop surgicalsafety id.
	 *
	 * @param surgeryChecklistId the surgery checklist id
	 * @param name the name
	 * @param order the order
	 * @param createdBy the created by
	 * @param createdTime the created time
	 * @param updatedBy the updated by
	 * @param updatedTime the updated time
	 */
	public IntraopSurgicalsafetyId(Integer surgeryChecklistId, String name, Integer order, String createdBy,
	        Date createdTime, String updatedBy, Date updatedTime)
	{
		this.surgeryChecklistId = surgeryChecklistId;
		this.name = name;
		this.order = order;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
	}

	/** The Constant serialVersionUID. */
	private static final long serialVersionUID = 1L;
	
	/**
	 * Gets the surgery checklist id.
	 *
	 * @return the surgery checklist id
	 */
	@Column(name = "SurgeryChecklistID")
	public Integer getSurgeryChecklistId()
	{
		return this.surgeryChecklistId;
	}

	/**
	 * Sets the surgery checklist id.
	 *
	 * @param surgeryChecklistId the new surgery checklist id
	 */
	public void setSurgeryChecklistId(Integer surgeryChecklistId)
	{
		this.surgeryChecklistId = surgeryChecklistId;
	}

	/**
	 * Gets the name.
	 *
	 * @return the name
	 */
	@Column(name = "Name", length = 45)
	public String getName()
	{
		return this.name;
	}

	/**
	 * Sets the name.
	 *
	 * @param name the new name
	 */
	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * Gets the order.
	 *
	 * @return the order
	 */
	@Column(name = "Order")
	public Integer getOrder()
	{
		return this.order;
	}

	/**
	 * Sets the order.
	 *
	 * @param order the new order
	 */
	public void setOrder(Integer order)
	{
		this.order = order;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "CreatedBy", length = 45)
	public String getCreatedBy()
	{
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Gets the created time.
	 *
	 * @return the created time
	 */
	@Column(name = "CreatedTime", length = 19)
	public Date getCreatedTime()
	{
		return this.createdTime;
	}

	/**
	 * Sets the created time.
	 *
	 * @param createdTime the new created time
	 */
	public void setCreatedTime(Date createdTime)
	{
		this.createdTime = createdTime;
	}

	/**
	 * Gets the updated by.
	 *
	 * @return the updated by
	 */
	@Column(name = "UpdatedBy", length = 45)
	public String getUpdatedBy()
	{
		return this.updatedBy;
	}

	/**
	 * Sets the updated by.
	 *
	 * @param updatedBy the new updated by
	 */
	public void setUpdatedBy(String updatedBy)
	{
		this.updatedBy = updatedBy;
	}

	/**
	 * Gets the updated time.
	 *
	 * @return the updated time
	 */
	@Column(name = "UpdatedTime", length = 19)
	public Date getUpdatedTime()
	{
		return this.updatedTime;
	}

	/**
	 * Sets the updated time.
	 *
	 * @param updatedTime the new updated time
	 */
	public void setUpdatedTime(Date updatedTime)
	{
		this.updatedTime = updatedTime;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IntraopSurgicalsafetyId))
			return false;
		IntraopSurgicalsafetyId castOther = (IntraopSurgicalsafetyId) other;

		return ((this.getSurgeryChecklistId() == castOther.getSurgeryChecklistId())
		        || (this.getSurgeryChecklistId() != null && castOther.getSurgeryChecklistId() != null
		                && this.getSurgeryChecklistId().equals(castOther.getSurgeryChecklistId())))
		        && ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
		                && this.getName().equals(castOther.getName())))
		        && ((this.getOrder() == castOther.getOrder()) || (this.getOrder() != null
		                && castOther.getOrder() != null && this.getOrder().equals(castOther.getOrder())))
		        && ((this.getCreatedBy() == castOther.getCreatedBy()) || (this.getCreatedBy() != null
		                && castOther.getCreatedBy() != null && this.getCreatedBy().equals(castOther.getCreatedBy())))
		        && ((this.getCreatedTime() == castOther.getCreatedTime())
		                || (this.getCreatedTime() != null && castOther.getCreatedTime() != null
		                        && this.getCreatedTime().equals(castOther.getCreatedTime())))
		        && ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this.getUpdatedBy() != null
		                && castOther.getUpdatedBy() != null && this.getUpdatedBy().equals(castOther.getUpdatedBy())))
		        && ((this.getUpdatedTime() == castOther.getUpdatedTime())
		                || (this.getUpdatedTime() != null && castOther.getUpdatedTime() != null
		                        && this.getUpdatedTime().equals(castOther.getUpdatedTime())));
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode()
	{
		int result = 17;

		result = 37 * result + (getSurgeryChecklistId() == null ? 0 : this.getSurgeryChecklistId().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getOrder() == null ? 0 : this.getOrder().hashCode());
		result = 37 * result + (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result + (getCreatedTime() == null ? 0 : this.getCreatedTime().hashCode());
		result = 37 * result + (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result + (getUpdatedTime() == null ? 0 : this.getUpdatedTime().hashCode());
		return result;
	}

}
