/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Oct 31, 2017 3:56:18 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;

/**
 * Investigationmeasuringunitratios generated by hbm2java
 */
@Entity
@Table(name = "investigationmeasuringunitratios", catalog = "intraop_dev")
public class Investigationmeasuringunitratios implements java.io.Serializable {

	private Integer investigationMeasuringUnitRatiosId;
	private Investigationmeasuringunits numeratorUnit;
	private Integer numeratorUnitExponent;
	private Investigationmeasuringunits denominatorUnit;
	private Integer denominatorUnitExponent;

	public Investigationmeasuringunitratios() {
	}

	public Investigationmeasuringunitratios(Investigationmeasuringunits numeratorUnit, Integer numeratorUnitExponent,
			Investigationmeasuringunits denominatorUnit, Integer denominatorUnitExponent) {
		this.numeratorUnit = numeratorUnit;
		this.numeratorUnitExponent = numeratorUnitExponent;
		this.denominatorUnit = denominatorUnit;
		this.denominatorUnitExponent = denominatorUnitExponent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "InvestigationMeasuringUnitRatiosID", unique = true, nullable = false)
	public Integer getInvestigationMeasuringUnitRatiosId() {
		return this.investigationMeasuringUnitRatiosId;
	}

	public void setInvestigationMeasuringUnitRatiosId(Integer investigationMeasuringUnitRatiosId) {
		this.investigationMeasuringUnitRatiosId = investigationMeasuringUnitRatiosId;
	}
	@ManyToOne
	@Fetch(org.hibernate.annotations.FetchMode.JOIN)
	@JoinColumn(name = "NumeratorUnitID")
	public Investigationmeasuringunits getNumeratorUnit() {
		return this.numeratorUnit;
	}

	public void setNumeratorUnit(Investigationmeasuringunits numeratorUnit) {
		this.numeratorUnit = numeratorUnit;
	}

	@Column(name = "NumeratorUnitExponent")
	public Integer getNumeratorUnitExponent() {
		return this.numeratorUnitExponent;
	}

	public void setNumeratorUnitExponent(Integer numeratorUnitExponent) {
		this.numeratorUnitExponent = numeratorUnitExponent;
	}
	@ManyToOne
	@Fetch(org.hibernate.annotations.FetchMode.JOIN)
	@JoinColumn(name = "DenominatorUnitID")
	public Investigationmeasuringunits getDenominatorUnit() {
		return this.denominatorUnit;
	}

	public void setDenominatorUnit(Investigationmeasuringunits denominatorUnit) {
		this.denominatorUnit = denominatorUnit;
	}

	@Column(name = "DenominatorUnitExponent")
	public Integer getDenominatorUnitExponent() {
		return this.denominatorUnitExponent;
	}

	public void setDenominatorUnitExponent(Integer denominatorUnitExponent) {
		this.denominatorUnitExponent = denominatorUnitExponent;
	}

}
