/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Oct 31, 2017 3:22:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Investigationstestparametersparent generated by hbm2java
 */
@Entity
@Table(name = "investigationstestparametersparent", catalog = "intraop_dev")
public class Investigationstestparametersparent implements java.io.Serializable {

	private Integer investigationsTestParametersParentId;
	private String parentName;

	public Investigationstestparametersparent() {
	}

	public Investigationstestparametersparent(String parentName) {
		this.parentName = parentName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "InvestigationsTestParametersParentID", unique = true, nullable = false)
	public Integer getInvestigationsTestParametersParentId() {
		return this.investigationsTestParametersParentId;
	}

	public void setInvestigationsTestParametersParentId(Integer investigationsTestParametersParentId) {
		this.investigationsTestParametersParentId = investigationsTestParametersParentId;
	}

	@Column(name = "ParentName", length = 100)
	public String getParentName() {
		return this.parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}

}
