/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 12, 2017 10:07:52 AM by Hibernate Tools 4.3.1.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

// TODO: Auto-generated Javadoc
/**
 * Pac generated by hbm2java.
 */
@Entity
@Table(name = "pac", catalog = "intraop_dev", uniqueConstraints = @UniqueConstraint(columnNames = "CaseID"))
public class Pac implements java.io.Serializable
{

	/** The pacid. */
	private Integer pacid;
	
	/** The patient. */
	private Patient patient;
	
	/** The patientcase. */
	private Patientcase patientcase;
	
	/** The created by. */
	private String createdBy;
	
	/** The created date time. */
	private Date createdDateTime;
	
	/** The updated by. */
	private String updatedBy;
	
	/** The updated date time. */
	private Date updatedDateTime;

	/**
	 * Instantiates a new pac.
	 */
	public Pac()
	{
	}

	/**
	 * Instantiates a new pac.
	 *
	 * @param patient the patient
	 * @param patientcase the patientcase
	 * @param createdBy the created by
	 * @param createdDateTime the created date time
	 */
	public Pac(Patient patient, Patientcase patientcase, String createdBy, Date createdDateTime)
	{
		this.patient = patient;
		this.patientcase = patientcase;
		this.createdBy = createdBy;
		this.createdDateTime = createdDateTime;
	}

	/**
	 * Instantiates a new pac.
	 *
	 * @param patient the patient
	 * @param patientcase the patientcase
	 * @param createdBy the created by
	 * @param createdDateTime the created date time
	 * @param updatedBy the updated by
	 * @param updatedDateTime the updated date time
	 */
	public Pac(Patient patient, Patientcase patientcase, String createdBy, Date createdDateTime, String updatedBy,
	        Date updatedDateTime)
	{
		this.patient = patient;
		this.patientcase = patientcase;
		this.createdBy = createdBy;
		this.createdDateTime = createdDateTime;
		this.updatedBy = updatedBy;
		this.updatedDateTime = updatedDateTime;
	}

	/**
	 * Gets the pacid.
	 *
	 * @return the pacid
	 */
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "PACID", unique = true, nullable = false)
	public Integer getPacid()
	{
		return this.pacid;
	}

	/**
	 * Sets the pacid.
	 *
	 * @param pacid the new pacid
	 */
	public void setPacid(Integer pacid)
	{
		this.pacid = pacid;
	}

	/**
	 * Gets the patient.
	 *
	 * @return the patient
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PatientID", nullable = false)
	public Patient getPatient()
	{
		return this.patient;
	}

	/**
	 * Sets the patient.
	 *
	 * @param patient the new patient
	 */
	public void setPatient(Patient patient)
	{
		this.patient = patient;
	}

	/**
	 * Gets the patientcase.
	 *
	 * @return the patientcase
	 */
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CaseID", unique = true, nullable = false)
	public Patientcase getPatientcase()
	{
		return this.patientcase;
	}

	/**
	 * Sets the patientcase.
	 *
	 * @param patientcase the new patientcase
	 */
	public void setPatientcase(Patientcase patientcase)
	{
		this.patientcase = patientcase;
	}

	/**
	 * Gets the created by.
	 *
	 * @return the created by
	 */
	@Column(name = "CreatedBy", nullable = false, length = 50)
	public String getCreatedBy()
	{
		return this.createdBy;
	}

	/**
	 * Sets the created by.
	 *
	 * @param createdBy the new created by
	 */
	public void setCreatedBy(String createdBy)
	{
		this.createdBy = createdBy;
	}

	/**
	 * Gets the created date time.
	 *
	 * @return the created date time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedDateTime", nullable = false, length = 19)
	public Date getCreatedDateTime()
	{
		return this.createdDateTime;
	}

	/**
	 * Sets the created date time.
	 *
	 * @param createdDateTime the new created date time
	 */
	public void setCreatedDateTime(Date createdDateTime)
	{
		this.createdDateTime = createdDateTime;
	}

	/**
	 * Gets the updated by.
	 *
	 * @return the updated by
	 */
	@Column(name = "UpdatedBy", length = 50)
	public String getUpdatedBy()
	{
		return this.updatedBy;
	}

	/**
	 * Sets the updated by.
	 *
	 * @param updatedBy the new updated by
	 */
	public void setUpdatedBy(String updatedBy)
	{
		this.updatedBy = updatedBy;
	}

	/**
	 * Gets the updated date time.
	 *
	 * @return the updated date time
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedDateTime", length = 19)
	public Date getUpdatedDateTime()
	{
		return this.updatedDateTime;
	}

	/**
	 * Sets the updated date time.
	 *
	 * @param updatedDateTime the new updated date time
	 */
	public void setUpdatedDateTime(Date updatedDateTime)
	{
		this.updatedDateTime = updatedDateTime;
	}

}
