/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Sep 18, 2017 11:16:42 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Procedurecategory generated by hbm2java
 */
@Entity
@Table(name = "procedurecategory", catalog = "intraop_dev")
public class Procedurecategory implements java.io.Serializable
{

	private Integer procedureCategoryId;
	private String procedureCategoryCode;
	private String procedureCategoryValue;
	private String icdversion;

	public Procedurecategory()
	{
	}

	public Procedurecategory(String procedureCategoryCode, String procedureCategoryValue, String icdversion)
	{
		this.procedureCategoryCode = procedureCategoryCode;
		this.procedureCategoryValue = procedureCategoryValue;
		this.icdversion = icdversion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ProcedureCategoryID", unique = true, nullable = false)
	public Integer getProcedureCategoryId()
	{
		return this.procedureCategoryId;
	}

	public void setProcedureCategoryId(Integer procedureCategoryId)
	{
		this.procedureCategoryId = procedureCategoryId;
	}

	@Column(name = "ProcedureCategoryCode", length = 10)
	public String getProcedureCategoryCode()
	{
		return this.procedureCategoryCode;
	}

	public void setProcedureCategoryCode(String procedureCategoryCode)
	{
		this.procedureCategoryCode = procedureCategoryCode;
	}

	@Column(name = "ProcedureCategoryValue", length = 200)
	public String getProcedureCategoryValue()
	{
		return this.procedureCategoryValue;
	}

	public void setProcedureCategoryValue(String procedureCategoryValue)
	{
		this.procedureCategoryValue = procedureCategoryValue;
	}

	@Column(name = "ICDVersion", length = 25)
	public String getIcdversion()
	{
		return this.icdversion;
	}

	public void setIcdversion(String icdversion)
	{
		this.icdversion = icdversion;
	}

}
