/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Jan 5, 2018 10:47:50 AM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.cdac.common.GeneratedEntities.Patient;
import com.cdac.common.GeneratedEntities.Patientcase;

/**
 * Recoveryroomreadings generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "recoveryroomreadings", catalog = "intraop_dev")
public class Recoveryroomreadings implements java.io.Serializable {
	
	private Integer recoveryRoomReadingRecordId;
	private Patientcase patientcase;
	private Patient patient;
	private String inVitalsBp;
	private BigDecimal inVitalsPulse;
	private BigDecimal inVitalsSpo2;
	private BigDecimal inVitalsResp;
	private BigDecimal inVitalsTemp;
	private String respSupport;
	private boolean ivlineInoTrops;
	private String ivlineInoTropsDetails;
	private boolean ivlineBlood;
	private String ivlineBloodDetails;
	private boolean ivlineIvfluids;
	private String ivlineIvfluidsDetails;
	private boolean ivlineInfusion;
	private String ivlineInfusionDetails;
	private String shiftingTo;
	private Integer aldreteScoreAtShiftingToPacu;
	private Date pacuTime;
	private Date shiftingOutTime;
	private BigDecimal outVitalsBp;
	private BigDecimal outVitalsPulse;
	private BigDecimal outVitalsSpo2;
	private BigDecimal outVitalsResp;
	private BigDecimal outVitalsTemp;
	private Integer modifiedAldreteScoreAtDischarge;
	private boolean specialInstructions;
	private String specialInstructionsDetails;
	private boolean anySpecialEventDuringStayinPacu;
	private String anySpecialEventDuringStayinPacudetails;
	private boolean investigation;
	private String investigationDetails;
	private boolean consultation;
	private String consultationDetails;
	private boolean drugs;
	private String drugsDetails;
	private boolean complications;
	private String complicationsDetails;
	private String createdBy;
	private Date createdTime;
	private String updatedBy;
	private Date updatedTime;
	private String pacuParams;
	private String shiftingOutParams;

	//changes done by Rohi
	private String pacingSupport;
	private BigDecimal beatsPerMinutes;
	private String leads;
	private String mode;
	private String negativeSuction;
	private String pleural;
	private BigDecimal inotropicScore;
	private String bleedingIssues;
	private String ba;
	private String rs_pc;


	// changes end
	private BigDecimal upperRange;
	private BigDecimal lowerRange;
	private BigDecimal areaUnderCurve;

	public Recoveryroomreadings() {
	}



	public Recoveryroomreadings(Integer recoveryRoomReadingRecordId, Patientcase patientcase, Patient patient,
			String inVitalsBp, BigDecimal inVitalsPulse, BigDecimal inVitalsSpo2, BigDecimal inVitalsResp,
			BigDecimal inVitalsTemp, String respSupport, boolean ivlineInoTrops, String ivlineInoTropsDetails,
			boolean ivlineBlood, String ivlineBloodDetails, boolean ivlineIvfluids, String ivlineIvfluidsDetails,
			boolean ivlineInfusion, String ivlineInfusionDetails, String shiftingTo,
			Integer aldreteScoreAtShiftingToPacu, Date shiftingOutTime, BigDecimal outVitalsBp,
			BigDecimal outVitalsPulse, BigDecimal outVitalsSpo2, BigDecimal outVitalsResp, BigDecimal outVitalsTemp,
			Integer modifiedAldreteScoreAtDischarge, boolean specialInstructions, String specialInstructionsDetails,
			boolean anySpecialEventDuringStayinPacu, String anySpecialEventDuringStayinPacudetails,
			boolean investigation, String investigationDetails, boolean consultation, String consultationDetails,
			boolean drugs, String drugsDetails, boolean complications, String complicationsDetails, String createdBy,
			Date createdTime, String updatedBy, Date updatedTime,String pacingSupport,BigDecimal beatsPerMinutes,String leads,String mode,String negativeSuction,String pleural,BigDecimal inotropicScore,String bleedingIssues,String ba,String rs_pc, BigDecimal areaUnderCurve) {
		super();
		this.recoveryRoomReadingRecordId = recoveryRoomReadingRecordId;
		this.patientcase = patientcase;
		this.patient = patient;
		this.inVitalsBp = inVitalsBp;
		this.inVitalsPulse = inVitalsPulse;
		this.inVitalsSpo2 = inVitalsSpo2;
		this.inVitalsResp = inVitalsResp;
		this.inVitalsTemp = inVitalsTemp;
		this.respSupport = respSupport;
		this.ivlineInoTrops = ivlineInoTrops;
		this.ivlineInoTropsDetails = ivlineInoTropsDetails;
		this.ivlineBlood = ivlineBlood;
		this.ivlineBloodDetails = ivlineBloodDetails;
		this.ivlineIvfluids = ivlineIvfluids;
		this.ivlineIvfluidsDetails = ivlineIvfluidsDetails;
		this.ivlineInfusion = ivlineInfusion;
		this.ivlineInfusionDetails = ivlineInfusionDetails;
		this.shiftingTo = shiftingTo;
		this.aldreteScoreAtShiftingToPacu = aldreteScoreAtShiftingToPacu;
		this.shiftingOutTime = shiftingOutTime;
		this.outVitalsBp = outVitalsBp;
		this.outVitalsPulse = outVitalsPulse;
		this.outVitalsSpo2 = outVitalsSpo2;
		this.outVitalsResp = outVitalsResp;
		this.outVitalsTemp = outVitalsTemp;
		this.modifiedAldreteScoreAtDischarge = modifiedAldreteScoreAtDischarge;
		this.specialInstructions = specialInstructions;
		this.specialInstructionsDetails = specialInstructionsDetails;
		this.anySpecialEventDuringStayinPacu = anySpecialEventDuringStayinPacu;
		this.anySpecialEventDuringStayinPacudetails = anySpecialEventDuringStayinPacudetails;
		this.investigation = investigation;
		this.investigationDetails = investigationDetails;
		this.consultation = consultation;
		this.consultationDetails = consultationDetails;
		this.drugs = drugs;
		this.drugsDetails = drugsDetails;
		this.complications = complications;
		this.complicationsDetails = complicationsDetails;
		this.createdBy = createdBy;
		this.createdTime = createdTime;
		this.updatedBy = updatedBy;
		this.updatedTime = updatedTime;
		this.pacingSupport=pacingSupport;
		this.beatsPerMinutes=beatsPerMinutes;
		this.leads=leads;
		this.mode=mode;
		this.negativeSuction=negativeSuction;
		this.pleural=pleural;
		this.inotropicScore=inotropicScore;
		this.bleedingIssues=bleedingIssues;
		this.ba =ba;
		this.rs_pc= rs_pc;
		this.areaUnderCurve = areaUnderCurve;
	}



	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "RecoveryRoomReadingRecordID", unique = true, nullable = false)
	public Integer getRecoveryRoomReadingRecordId() {
		return this.recoveryRoomReadingRecordId;
	}

	public void setRecoveryRoomReadingRecordId(Integer recoveryRoomReadingRecordId) {
		this.recoveryRoomReadingRecordId = recoveryRoomReadingRecordId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CaseID", nullable = false)
	public Patientcase getPatientcase() {
		return this.patientcase;
	}

	public void setPatientcase(Patientcase patientcase) {
		this.patientcase = patientcase;
	}

	@ManyToOne
	@JoinColumn(name = "CRNumber", referencedColumnName = "CRNumber", nullable = false)
	public Patient getPatient() {
		return patient;
	}

	public void setPatient(Patient patient) {
		this.patient = patient;
	}

	@Column(name = "InVitalsBP", precision = 5)
	public String getInVitalsBp() {
		return this.inVitalsBp;
	}

	public void setInVitalsBp(String inVitalsBp) {
		this.inVitalsBp = inVitalsBp;
	}

	@Column(name = "InVitalsPulse", precision = 5)
	public BigDecimal getInVitalsPulse() {
		return this.inVitalsPulse;
	}

	public void setInVitalsPulse(BigDecimal inVitalsPulse) {
		this.inVitalsPulse = inVitalsPulse;
	}

	@Column(name = "InVitalsSPO2", precision = 5)
	public BigDecimal getInVitalsSpo2() {
		return this.inVitalsSpo2;
	}

	public void setInVitalsSpo2(BigDecimal inVitalsSpo2) {
		this.inVitalsSpo2 = inVitalsSpo2;
	}

	@Column(name = "InVitalsResp", precision = 5)
	public BigDecimal getInVitalsResp() {
		return this.inVitalsResp;
	}

	public void setInVitalsResp(BigDecimal inVitalsResp) {
		this.inVitalsResp = inVitalsResp;
	}

	@Column(name = "InVitalsTemp", precision = 5)
	public BigDecimal getInVitalsTemp() {
		return this.inVitalsTemp;
	}

	public void setInVitalsTemp(BigDecimal inVitalsTemp) {
		this.inVitalsTemp = inVitalsTemp;
	}

	@Column(name = "RespSupport", length = 200)
	public String getRespSupport() {
		return this.respSupport;
	}

	public void setRespSupport(String respSupport) {
		this.respSupport = respSupport;
	}

	@Column(name = "IVLineInoTrops")
	public boolean getIvlineInoTrops() {
		return this.ivlineInoTrops;
	}

	public void setIvlineInoTrops(boolean ivlineInoTrops) {
		this.ivlineInoTrops = ivlineInoTrops;
	}

	@Column(name = "IVLineInoTropsDetails", length = 2000)
	public String getIvlineInoTropsDetails() {
		return this.ivlineInoTropsDetails;
	}

	public void setIvlineInoTropsDetails(String ivlineInoTropsDetails) {
		this.ivlineInoTropsDetails = ivlineInoTropsDetails;
	}

	@Column(name = "IVLineBlood")
	public boolean getIvlineBlood() {
		return this.ivlineBlood;
	}

	public void setIvlineBlood(boolean ivlineBlood) {
		this.ivlineBlood = ivlineBlood;
	}

	@Column(name = "IVLineBloodDetails", length = 2000)
	public String getIvlineBloodDetails() {
		return this.ivlineBloodDetails;
	}

	public void setIvlineBloodDetails(String ivlineBloodDetails) {
		this.ivlineBloodDetails = ivlineBloodDetails;
	}

	@Column(name = "IVLineIVFluids")
	public boolean getIvlineIvfluids() {
		return this.ivlineIvfluids;
	}

	public void setIvlineIvfluids(boolean ivlineIvfluids) {
		this.ivlineIvfluids = ivlineIvfluids;
	}

	@Column(name = "IVLineIVFluidsDetails", length = 2000)
	public String getIvlineIvfluidsDetails() {
		return this.ivlineIvfluidsDetails;
	}

	public void setIvlineIvfluidsDetails(String ivlineIvfluidsDetails) {
		this.ivlineIvfluidsDetails = ivlineIvfluidsDetails;
	}

	@Column(name = "IVLineInfusion")
	public boolean getIvlineInfusion() {
		return this.ivlineInfusion;
	}

	public void setIvlineInfusion(boolean ivlineInfusion) {
		this.ivlineInfusion = ivlineInfusion;
	}

	@Column(name = "IVLineInfusionDetails", length = 2000)
	public String getIvlineInfusionDetails() {
		return this.ivlineInfusionDetails;
	}

	public void setIvlineInfusionDetails(String ivlineInfusionDetails) {
		this.ivlineInfusionDetails = ivlineInfusionDetails;
	}

	@Column(name = "ShiftingTo", length = 45)
	public String getShiftingTo() {
		return this.shiftingTo;
	}

	public void setShiftingTo(String shiftingTo) {
		this.shiftingTo = shiftingTo;
	}

	@Column(name = "AldreteScoreAtShiftingToPACU")
	public Integer getAldreteScoreAtShiftingToPacu() {
		return this.aldreteScoreAtShiftingToPacu;
	}

	public void setAldreteScoreAtShiftingToPacu(Integer aldreteScoreAtShiftingToPacu) {
		this.aldreteScoreAtShiftingToPacu = aldreteScoreAtShiftingToPacu;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "PACUTime", length = 19)
	public Date getPacuTime() {
		return pacuTime;
	}
	public void setPacuTime(Date pacuTime) {
		this.pacuTime = pacuTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ShiftingOutTime", length = 19)
	public Date getShiftingOutTime() {
		return this.shiftingOutTime;
	}

	public void setShiftingOutTime(Date shiftingOutTime) {
		this.shiftingOutTime = shiftingOutTime;
	}

	@Column(name = "OutVitalsBP", precision = 5)
	public BigDecimal getOutVitalsBp() {
		return this.outVitalsBp;
	}

	public void setOutVitalsBp(BigDecimal outVitalsBp) {
		this.outVitalsBp = outVitalsBp;
	}

	@Column(name = "OutVitalsPulse", precision = 5)
	public BigDecimal getOutVitalsPulse() {
		return this.outVitalsPulse;
	}

	public void setOutVitalsPulse(BigDecimal outVitalsPulse) {
		this.outVitalsPulse = outVitalsPulse;
	}

	@Column(name = "OutVitalsSPO2", precision = 5)
	public BigDecimal getOutVitalsSpo2() {
		return this.outVitalsSpo2;
	}

	public void setOutVitalsSpo2(BigDecimal outVitalsSpo2) {
		this.outVitalsSpo2 = outVitalsSpo2;
	}

	@Column(name = "OutVitalsResp", precision = 5)
	public BigDecimal getOutVitalsResp() {
		return this.outVitalsResp;
	}

	public void setOutVitalsResp(BigDecimal outVitalsResp) {
		this.outVitalsResp = outVitalsResp;
	}

	@Column(name = "OutVitalsTemp", precision = 5)
	public BigDecimal getOutVitalsTemp() {
		return this.outVitalsTemp;
	}

	public void setOutVitalsTemp(BigDecimal outVitalsTemp) {
		this.outVitalsTemp = outVitalsTemp;
	}

	@Column(name = "ModifiedAldreteScoreAtDischarge")
	public Integer getModifiedAldreteScoreAtDischarge() {
		return this.modifiedAldreteScoreAtDischarge;
	}

	public void setModifiedAldreteScoreAtDischarge(Integer modifiedAldreteScoreAtDischarge) {
		this.modifiedAldreteScoreAtDischarge = modifiedAldreteScoreAtDischarge;
	}

	@Column(name = "SpecialInstructions")
	public boolean getSpecialInstructions() {
		return this.specialInstructions;
	}

	public void setSpecialInstructions(boolean specialInstructions) {
		this.specialInstructions = specialInstructions;
	}

	@Column(name = "SpecialInstructionsDetails", length = 2000)
	public String getSpecialInstructionsDetails() {
		return this.specialInstructionsDetails;
	}

	public void setSpecialInstructionsDetails(String specialInstructionsDetails) {
		this.specialInstructionsDetails = specialInstructionsDetails;
	}

	@Column(name = "AnySpecialEventDuringStayinPACU")
	public boolean getAnySpecialEventDuringStayinPacu() {
		return this.anySpecialEventDuringStayinPacu;
	}

	public void setAnySpecialEventDuringStayinPacu(boolean anySpecialEventDuringStayinPacu) {
		this.anySpecialEventDuringStayinPacu = anySpecialEventDuringStayinPacu;
	}

	@Column(name = "AnySpecialEventDuringStayinPACUDetails", length = 2000)
	public String getAnySpecialEventDuringStayinPacudetails() {
		return this.anySpecialEventDuringStayinPacudetails;
	}

	public void setAnySpecialEventDuringStayinPacudetails(String anySpecialEventDuringStayinPacudetails) {
		this.anySpecialEventDuringStayinPacudetails = anySpecialEventDuringStayinPacudetails;
	}

	@Column(name = "Investigation")
	public boolean getInvestigation() {
		return this.investigation;
	}

	public void setInvestigation(boolean investigation) {
		this.investigation = investigation;
	}

	@Column(name = "InvestigationDetails", length = 2000)
	public String getInvestigationDetails() {
		return this.investigationDetails;
	}

	public void setInvestigationDetails(String investigationDetails) {
		this.investigationDetails = investigationDetails;
	}

	@Column(name = "Consultation")
	public boolean getConsultation() {
		return this.consultation;
	}

	public void setConsultation(boolean consultation) {
		this.consultation = consultation;
	}

	@Column(name = "ConsultationDetails", length = 2000)
	public String getConsultationDetails() {
		return this.consultationDetails;
	}

	public void setConsultationDetails(String consultationDetails) {
		this.consultationDetails = consultationDetails;
	}

	@Column(name = "Drugs")
	public boolean getDrugs() {
		return this.drugs;
	}

	public void setDrugs(boolean drugs) {
		this.drugs = drugs;
	}

	@Column(name = "DrugsDetails", length = 2000)
	public String getDrugsDetails() {
		return this.drugsDetails;
	}

	public void setDrugsDetails(String drugsDetails) {
		this.drugsDetails = drugsDetails;
	}

	@Column(name = "Complications")
	public boolean getComplications() {
		return this.complications;
	}

	public void setComplications(boolean complications) {
		this.complications = complications;
	}

	@Column(name = "ComplicationsDetails", length = 2000)
	public String getComplicationsDetails() {
		return this.complicationsDetails;
	}

	public void setComplicationsDetails(String complicationsDetails) {
		this.complicationsDetails = complicationsDetails;
	}

	@Column(name = "CreatedBy", length = 45)
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CreatedTime", length = 19)
	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	@Column(name = "UpdatedBy", length = 45)
	public String getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(String updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UpdatedTime", length = 19)
	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}


	@Column(name = "PACUParams", length = 45)
	public String getPacuParams() {
		return pacuParams;
	}



	public void setPacuParams(String pacuParams) {
		this.pacuParams = pacuParams;
	}


	@Column(name = "ShiftingOutParams", length = 45)
	public String getShiftingOutParams() {
		return shiftingOutParams;
	}



	public void setShiftingOutParams(String shiftingOutParams) {
		this.shiftingOutParams = shiftingOutParams;
	}


// changes done by Rohi
	@Column(name = "PacingSupport", length = 45)
	public String getPacingSupport() {
		return pacingSupport;
	}



	public void setPacingSupport(String pacingSupport) {
		this.pacingSupport = pacingSupport;
	}



	@Column(name = "Leads", length = 45)
	public String getLeads() {
		return leads;
	}



	public void setLeads(String leads) {
		this.leads = leads;
	}


	@Column(name = "Mode", length = 45)
	public String getMode() {
		return mode;
	}



	public void setMode(String mode) {
		this.mode = mode;
	}


	@Column(name = "NegativeSuction", length = 45)
	public String getNegativeSuction() {
		return negativeSuction;
	}



	public void setNegativeSuction(String negativeSuction) {
		this.negativeSuction = negativeSuction;
	}




	@Column(name = "Pleural", length = 45)
	public String getPleural() {
		return pleural;
	}



	public void setPleural(String pleural) {
		this.pleural = pleural;
	}


	@Column(name = "InotropicScore", precision = 5)
	public BigDecimal getInotropicScore() {
		return inotropicScore;
	}



	public void setInotropicScore(BigDecimal inotropicScore) {
		this.inotropicScore = inotropicScore;
	}


	@Column(name = "BleedingIssues", length = 45)
	public String getBleedingIssues() {
		return bleedingIssues;
	}



	public void setBleedingIssues(String bleedingIssues) {
		this.bleedingIssues = bleedingIssues;
	}


	@Column(name = "BeatsPerMinutes", precision = 5)
	public BigDecimal getBeatsPerMinutes() {
		return beatsPerMinutes;
	}



	public void setBeatsPerMinutes(BigDecimal beatsPerMinutes) {
		this.beatsPerMinutes = beatsPerMinutes;
	}


	@Column(name = "Backup_Active", length = 45)
	public String getBa() {
		return ba;
	}



	public void setBa(String ba) {
		this.ba = ba;
	}


	@Column(name = "Rs_Pc", length = 45)
	public String getRs_pc() {
		return rs_pc;
	}



	public void setRs_pc(String rs_pc) {
		this.rs_pc = rs_pc;
	}


	@Column(name = "AreaUnderCurve", precision = 5)
	public BigDecimal getAreaUnderCurve() {
		return this.areaUnderCurve;
	}

	public void setAreaUnderCurve(BigDecimal areaUnderCurve) {
		this.areaUnderCurve = areaUnderCurve;
	}


	@Column(name = "UpperRange", precision = 5)
	public BigDecimal getUpperRange() {
		return upperRange;
	}



	public void setUpperRange(BigDecimal upperRange) {
		this.upperRange = upperRange;
	}


	@Column(name = "LowerRange", precision = 5)
	public BigDecimal getLowerRange() {
		return lowerRange;
	}



	public void setLowerRange(BigDecimal lowerRange) {
		this.lowerRange = lowerRange;
	}

}
