/*******************************************************************************
 * � 2018-2019 Infosys Limited, Bangalore, India. All Rights Reserved. 
 * Version: 1.0.0.0
 *
 * This Program is protected by copyright laws, international treaties and other pending or existing intellectual property rights in India, the United States and other countries. Except as expressly permitted, any unauthorized reproduction, storage, transmission in any form or by any means (including without limitation electronic, mechanical, printing, photocopying, recording or otherwise), or any distribution of this Program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law. 
 *******************************************************************************/
package com.cdac.common.GeneratedEntities;
// Generated Oct 10, 2017 3:07:55 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usersinroles generated by hbm2java
 */
@Entity
@Table(name = "usersinroles", catalog = "intraop_dev", uniqueConstraints = @UniqueConstraint(columnNames = "UserId"))
public class Usersinroles implements java.io.Serializable {

	private Integer usersInRolesId;
	private int userId;
	private int roleId;

	public Usersinroles() {
	}

	public Usersinroles(int userId, int roleId) {
		this.userId = userId;
		this.roleId = roleId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UsersInRolesID", unique = true, nullable = false)
	public Integer getUsersInRolesId() {
		return this.usersInRolesId;
	}

	public void setUsersInRolesId(Integer usersInRolesId) {
		this.usersInRolesId = usersInRolesId;
	}

	@Column(name = "UserId", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "RoleId", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

}
